services:
  epic-bot:
    image: TUO_IMAGE
    container_name: epic-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=xxx
      - DISCORD_CHANNEL_ID=xxx
      - ITAD_API_KEY=LA_TUA_CHIAVE
      - ITAD_COUNTRY=IT
      - STEAM_MAX_FINAL_EUR=9
      - STEAM_MIN_DISCOUNT_PCT=50
      - STEAM_MAX_RESULTS=60
