services:
  epic-discord-bot:
    build: .
    container_name: epic-discord-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      CHECK_EVERY_MIN: ${CHECK_EVERY_MIN}
    volumes:
      - epicbot_data:/data

volumes:
  epicbot_data:
